// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_00_png);   // assets/00.png
LV_IMG_DECLARE( ui_img_04_png);   // assets/04.png
LV_IMG_DECLARE( ui_img_08_png);   // assets/08.png
LV_IMG_DECLARE( ui_img_12_png);   // assets/12.png
LV_IMG_DECLARE( ui_img_16_png);   // assets/16.png
LV_IMG_DECLARE( ui_img_20_png);   // assets/20.png


LV_FONT_DECLARE( ui_font_Font1);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
